"""
    store constants and settings here
        Daniel Bugelnig, 2025 (daniel.bugelnig@aau.at)
        Generated by Configuration GUI
"""

from .core.shared_data import State



"""        EXPOSED SETTINGS - MODIFY HERE (can be added to UI)        """

# operating system
OP_SYSTEM = "Linux"

# Wi-Fi, set the settings of the access point created by the host computer
WIFI_NAME = "ai_deck"
WIFI_PASSWORD = "bitcraze"




"""        OTHER CONSTANTS (hardcoded constants, shoudn't be changed from one run to another)        """
# List all crazyflies here with their URIs
CRAZYFLIES = ['radio://0/90/2M/E7E7E7E701', 'radio://0/90/2M/E7E7E7E702', 'radio://0/120/2M/E7E7E7E703', 'radio://0/90/2M/E7E7E7E704', 'radio://0/100/2M/E7E7E7E704']

# Lookup table for AI deck MAC addresses and drone addresses
MAC = ["-", # placeholder
    "78:21:84:7b:0f:58", #1 rgb
    "78:21:84:7a:4f:70", #2 rgb
    "78:21:84:7a:50:c8", #3 rgb
    "78:21:84:7b:0b:8c", #4 mono
]
MAC_LOOKUP = {
    "radio://0/120/2M/E7E7E7E701": "08:3a:f2:b0:a2:30",
}

RIGID_BODY_ID_LOOKUP = {'radio://0/90/2M/E7E7E7E701': 12, 'radio://0/90/2M/E7E7E7E702': 13, 'radio://0/120/2M/E7E7E7E703': 14, 'radio://0/90/2M/E7E7E7E704': 15}

# Positioning system settings
POSITIONING_SYSTEM = "OptiTrack"
CLIENT_IP = "192.168.1.143"
SERVER_IP = "192.168.1.171"
USE_MULTICAST = True

MOCAP_TX_RATE_HZ = 100
MOCAP_FRESH_MS = 150
MOCAP_SETTLE_S = 1.0
TIMEOUT = 5

CONTROLLER_TYPE = 1

MESHROOM_ROOT = ""
ALICE_VISION_ROOT = ""

FLYING_AREA = [State(x=-1.5, y=-1.0, z=0.1), State(x=1.5, y=-1.0, z=0.1), State(x=1.5, y=1.0, z=0.1), State(x=-1.5, y=1.0, z=0.1), State(x=-1.5, y=-1.0, z=2.0), State(x=1.5, y=-1.0, z=2.0), State(x=1.5, y=1.0, z=2.0), State(x=-1.5, y=1.0, z=2.0)]

WIFI_SOCKET_PORT = 5000

LOW_BATTERY = 2.5
RATED_CURRENT = 0.25
MAX_ANGLE_STEP = 45
ARRIVAL_THRESHOLD_DISTANCE = 0.15
ARRIVAL_THRESHOLD_ANGLE = 3
ARRIVAL_THRESHOLD_DISTANCE_ROUGH = 0.25
ARRIVAL_THRESHOLD_ANGLE_ROUGH = 8
DRONE_DELAY = 0.1
DECK_DELAY = 0.5
REPULSION_FACTOR = 0.1
ATTRACTION_FACTOR = 1.4
REPULSION_FACTOR_OBJECT = 10
REPULSION_FACTOR_DRONE = 0.1
REPULSION_FACTOR_WALL = 0.2
OBJECT_RADIUS = 0.3
WALL_RADIUS = 0.6
DRONE_RADIUS = 0.8
GOAL_RADIUS = 0.05
SPHERE_POINTS = 400
STEPSIZE = 0.01
RESOLUTION = 0.1
WINDOW_SIZE = 10
THRESHOLD = 0.05
RANDOM_WALK_FACTOR = 0.1

CAMERA = "RGB"
DISPLAY_IMAGES = True
